### ISSUE TITLE
Port vulkan renderer from ETe (Q3e).

### ISSUE THREAD

**Issue by KuehnhammerTobias** [KuehnhammerTobias/ioqw-devel#24]
See: https://github.com/etfdevs/ETe/issues/46
Vulkan runs very fast. Unfortunately Q3e's vulkan renderer only supports the very basic features of Spearmint's (ioquake3) OpenGL 2 renderer.
The whole fog enhancements, foliage support, RtCW shader support is missing for example. Even default OpenGL 2 features like the sun shadows are missing. I don't even know what normal/parallax methods Vulkan currently supports. How does iqm models work on Vulkan?
Probably the missing features are a part why Vulkan is that fast.
It's very likely porting vulkan is a task to big for me.

**Comment by ensiform** [comment]
There would be no ioquake3 OpenGL2 renderer features added to ETe Vulkan.

Foliage support in vbo was added so that should be easier to bring over.

Fog enhancements need to be completely rewritten for vulkan and such. as glFog\* funcs do not have an equivalent in code form. Fog parameter data must be sent to a shader somehow and updated when a change occurs.

**Comment by KuehnhammerTobias** [comment]
> There would be no ioquake3 OpenGL2 renderer features added to ETe Vulkan.

Ok, this changes everything, just supporting 1999 rendering tasks is pointless to do on Vulkan imo, even vQ3a's renderer1 works well nowadays.
It would be nice to see more modern features (at least parallax/normal mapping, RT-lights, etc.) to compare the renderers (especially Vulkan vs. OpenGL2). I was told thousand times that OpenGL2 is very bad and slow. For whatever reason I still can't confirm this, even on pure test maps with an unrealistic tris count like 'skrimter' etc.
Spearmint's GL2 is still the fastest renderer at least on NV for me, the renderer needs more hunkmegs though. Idk, unfortunately I'm really stupid concerning render programming.
Anyways, probably an alternate Vulkan implementation will come from here: https://github.com/RobertBeckebans/RBQUAKE-3#may-or-may-not-plan
Yeah, it seems the real beast is back! After ten years or so ;)
Anyways, thanks for the feedback ensiform, it will help me to decide to which engine to switch to...
I'm still interested in Ete though...

**Comment by KuehnhammerTobias** [comment]
https://github.com/KuehnhammerTobias/ioqw-devel/issues/31

**Comment by KuehnhammerTobias** [comment]
As long as Vulkan doesn't introduce any new next-gen-eye-candy features it doesn't make sense to switch to Vulkan imo. Especially because our current Spearmint renderer2 is not slower and has much more nice features.
This doesn't mean Vulkan is bad, it just means porting our current rendering features to Vulkan is out of our scope and I don't have the skills for this task.
